### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by antonatos** [ariasdiniz/csv_parser#4]
You can just do:
          current_item[current_index] = '\0';
before your 
        buffer[field_index] = current_item;

and also just before the function returns. This way you dont need to memset the buffers at the beginning of the function

**Comment by ariasdiniz** [comment]
Thanks for the suggestion, but I don't think this will solve the problem, since the other characters of the field will still hold garbage from previous iterations

**Comment by antonatos** [comment]
only one \0 is enough for the consumer. so if you have "test123\0garbagefrompreviousiteration\0" when someone reads that string (e.g strlen, strdup etc) they will get "test123"

**Comment by ariasdiniz** [comment]
Thanks for the suggestion!
